# Setup
title:               Abneyah
tagline:             'TechBlog'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://blog.abneyah.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mohammed
  url:               https://twitter.com/mdo
  email:             mohammed@abneyah.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-28475612-1
